### ISSUE TITLE
maximum number of matched individuals

### ISSUE THREAD

**Issue by anamariaUIC** [plger/iPSCpoweR#2]
Hello,

I am trying to run your function with teh following paramaters:
DEA.permutateIndividuals(nbIndividuals = 30, maxTests = 10, nbClone = 1, addDE=TRUE, ncores = 1,useOnlyMulticlone=FALSE)

I am getting this error:
Looking for combinations...
Error in combn(unique(m$individual[which(m$sex == x)]), sum(nbIndividuals)) : 
  n < m

This error says that 30 individuals, with one clone per individual could not be matched by sex.

I understand there is 107 individuals provided in GSE79636 sample set:

> dim(GSE79636$annotation)
[1] 107  21

and with this distribution of male/female:
Female   Male 
    68     39 

Can you please advise? So far I could run this function with the maximum number of 7 individuals? Is that the maximum number of individuals I can run with this sample data? 

Please advise,

Thanks
Ana

**Comment by plger** [comment]
There are 107 samples in the datasets, but much fewer individuals:
```
> m <- GSE79636$annotation
> table(m$Sex[!duplicated(m$individual)])

Female   Male 
    23     14 
```
Nevertheless, due to the implementation the code was limited to a maximum total number of individuals equal to the smallest sex (14). I've now pushed a fix that should allow you to go up to the real maximum ( 18 vs 18 ).
