### ISSUE TITLE
nbClone in permutateIndividuals

### ISSUE THREAD

**Issue by adinasarapu** [plger/iPSCpoweR#3]
**I have an issue with nbClone parameter.**

DEA.permutateIndividuals("nbIndividuals = 3, nbClone = 1): **Expecting 6 clones and 6 clones selected.**

  | V1 | V2 | V3 | V4 | V5 | V6 | sex.balanced
-- | -- | -- | -- | -- | -- | -- | --
1 | i178 | i23 | i514 | i703 | i81 | i843 | TRUE
2 | i110 | i448 | i514 | i703 | i71 | i762 | TRUE
3 | i291 | i668 | i688 | i703 | i771 | i865 | TRUE
4 | i120 | i336 | i514 | i762 | i771 | i987 | TRUE
5 | i291 | i410 | i546 | i551 | i703 | i843 | TRUE
6 | i120 | i448 | i459 | i72 | i865 | i987 | TRUE
7 | i123 | i24 | i243 | i448 | i546 | i780 | TRUE
8 | i135 | i178 | i459 | i460 | i546 | i771 | TRUE
9 | i441 | i459 | i546 | i668 | i688 | i780 | TRUE
10 | i24 | i291 | i334 | i441 | i551 | i952 | TRUE

1 | GSM2100010 | GSM2099964 | GSM2100145 | GSM2100102 | GSM2099983 | GSM2100233
-- | -- | -- | -- | -- | -- | --
2 | GSM2099990 | GSM2100124 | GSM2100145 | GSM2100103 | GSM2099976 | GSM2100203
3 | GSM2100046 | GSM2100182 | GSM2100187 | GSM2100102 | GSM2100209 | GSM2100245
4 | GSM2099994 | GSM2100062 | GSM2100144 | GSM2100203 | GSM2100209 | GSM2100268
5 | GSM2100048 | GSM2100091 | GSM2100155 | GSM2100158 | GSM2100102 | GSM2100233
6 | GSM2099994 | GSM2100122 | GSM2100125 | GSM2099981 | GSM2100245 | GSM2100269
7 | GSM2100001 | GSM2099966 | GSM2100033 | GSM2100122 | GSM2100157 | GSM2100213
8 | GSM2100006 | GSM2100009 | GSM2100127 | GSM2100128 | GSM2100157 | GSM2100210
9 | GSM2100113 | GSM2100127 | GSM2100156 | GSM2100183 | GSM2100185 | GSM2100212
10 | GSM2099967 | GSM2100046 | GSM2100058 | GSM2100113 | GSM2100160 | GSM2100259

DEA.permutateIndividuals("nbIndividuals = 3, nbClone = 2): **Expecting 12 clones but 17 or 18 clones selected.**

1 | GSM2099962 | GSM2099963 | GSM2099964 | GSM2100008 | GSM2100009 | GSM2100010 | GSM2100143 | GSM2100144 | GSM2100145 | GSM2099982 | GSM2099983 | GSM2099984 | GSM2100102 | GSM2100103 | GSM2100104 | GSM2100232 | GSM2100233 | GSM2100234
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2 | GSM2099990 | GSM2099991 | GSM2099992 | GSM2100122 | GSM2100123 | GSM2100124 | GSM2100143 | GSM2100144 | GSM2100145 | GSM2099976 | GSM2099977 | GSM2099978 | GSM2100102 | GSM2100103 | GSM2100104 | GSM2100202 | GSM2100203 | GSM2100204
3 | GSM2100046 | GSM2100047 | GSM2100048 | GSM2100182 | GSM2100183 | GSM2100184 | GSM2100185 | GSM2100186 | GSM2100187 | GSM2100102 | GSM2100103 | GSM2100104 | GSM2100208 | GSM2100209 | GSM2100210 | GSM2100244 | GSM2100245 | GSM2100246
4 | GSM2099993 | GSM2099994 | GSM2099995 | GSM2100061 | GSM2100062 | GSM2100063 | GSM2100143 | GSM2100144 | GSM2100145 | GSM2100202 | GSM2100203 | GSM2100204 | GSM2100208 | GSM2100209 | GSM2100210 | GSM2100268 | GSM2100269 | GSM2100270
5 | GSM2100046 | GSM2100047 | GSM2100048 | GSM2100089 | GSM2100090 | GSM2100091 | GSM2100155 | GSM2100156 | GSM2100157 | GSM2100102 | GSM2100103 | GSM2100104 | GSM2100158 | GSM2100160 | GSM2100232 | GSM2100233 | GSM2100234 |  
6 | GSM2099993 | GSM2099994 | GSM2099995 | GSM2100122 | GSM2100123 | GSM2100124 | GSM2100125 | GSM2100126 | GSM2100127 | GSM2099979 | GSM2099980 | GSM2099981 | GSM2100244 | GSM2100245 | GSM2100246 | GSM2100268 | GSM2100269 | GSM2100270
7 | GSM2099965 | GSM2099966 | GSM2099967 | GSM2099999 | GSM2100000 | GSM2100001 | GSM2100032 | GSM2100033 | GSM2100034 | GSM2100122 | GSM2100123 | GSM2100124 | GSM2100155 | GSM2100156 | GSM2100157 | GSM2100212 | GSM2100213 |  
8 | GSM2100005 | GSM2100006 | GSM2100007 | GSM2100008 | GSM2100009 | GSM2100010 | GSM2100125 | GSM2100126 | GSM2100127 | GSM2100128 | GSM2100129 | GSM2100130 | GSM2100155 | GSM2100156 | GSM2100157 | GSM2100208 | GSM2100209 | GSM2100210
9 | GSM2100111 | GSM2100112 | GSM2100113 | GSM2100125 | GSM2100126 | GSM2100127 | GSM2100155 | GSM2100156 | GSM2100157 | GSM2100182 | GSM2100183 | GSM2100184 | GSM2100185 | GSM2100186 | GSM2100187 | GSM2100212 | GSM2100213 |  
10 | GSM2099965 | GSM2099966 | GSM2099967 | GSM2100046 | GSM2100047 | GSM2100048 | GSM2100058 | GSM2100059 | GSM2100060 | GSM2100111 | GSM2100112 | GSM2100113 | GSM2100158 | GSM2100160 | GSM2100259 | GSM2100260 | GSM2100261 |  

DEA.permutateIndividuals("nbIndividuals = 3, nbClone = 3): **Here I want to use 3 clones per subject.**

Error in DEA.permutateIndividuals(returnResults = TRUE, nbIndividuals = 3,  : 
  nbClone should be either 1 or 2.

**In my actual data, I have 4 clones per subject. How to fix this issue?**

Thank you

**Comment by plger** [comment]
You're using GSE79636 I assume -- indeed there was a bug with this dataset when using 2 clones, I've pushed a fix and will update the benchmark in the next couple of days in case it makes a difference.
I've also enabled running with >2 clones per individual, however you'll be limited to 3 and to the GSE79636 dataset (the only one that has 3 clones for many individuals) unless you use your own dataset.

**Comment by adinasarapu** [comment]
Thank you. I have 4 clones per subject.
